DEFAULT_INITIAL_SLEEP_TIME = 0.01
DEFAULT_JITTER = .25 # percentage of current sleep time
DEFAULT_BACKOFF_FACTOR = 2.0
DEFAULT_NO_DELAY_TRIES = 2
DEFAULT_MAX_TRIES = 10 # or None for unlimited
DEFAULT_WAIT_TIMEOUT = .01
DEFAULT_OBJECT_SIZE = 1024

PICKLE_PROTOCOL = 2
